/* USER */
export const GOOGLE_LOGIN = 'GOOGLE_LOGIN'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTH_USER = 'AUTH_USER'
export const RESET_ERROR_LOGUIN_USER = 'RESET_ERROR_LOGUIN_USER'
export const VALIDATE_USER = 'VALIDATE_USER'
export const SEND_EMAIL_TO_RESET_PASSWORD = 'SEND_EMAIL_TO_RESET_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const RESET_ERROR = 'RESET_ERROR'
export const IS_ADMIN = 'IS_ADMIN'
export const UPDATE_NOMBRE = 'UPDATE_NOMBRE'
export const BORRAR_USUARIO = 'BORRAR_USUARIO'
export const ACTUAL = 'ACTUAL'

/* EVERYTHING ELSE... */