/* USER */
export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const AUTH_USER = "AUTH_USER";
export const RESET_ERROR_LOGUIN_USER = "RESET_ERROR_LOGUIN_USER";
export const VALIDATE_USER = "VALIDATE_USER";
export const SEND_EMAIL_TO_RESET_PASSWORD = "SEND_EMAIL_TO_RESET_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_ERROR = "RESET_ERROR";
export const IS_ADMIN = "IS_ADMIN";
export const UPDATE_NOMBRE = "UPDATE_NOMBRE";
export const BORRAR_USUARIO = "BORRAR_USUARIO";
export const ACTUAL = "ACTUAL";

/* CURSOS... */
export const UPDATE_CURSO = "UPDATE_CURSO";
export const DELETE_CURSO = "DELETE_CURSO";
export const GET_CURSOS = "GET_CURSOS";

/* MENTORIAS... */
export const GET_MENTORIAS = "GET_MENTORIAS";
export const POST_MENTORIAS = "POST_MENTORIAS";
export const PUT_MENTORIAS = "PUT_MENTORIAS";
export const DELETE_MENTORIAS = "DELETE_MENTORIAS";

/* ANUNCIOS... */
export const GET_ANUNCIOS = "GET_ANUNCIOS";
export const POST_ANUNCIOS = "POST_ANUNCIOS";
export const PUT_ANUNCIOS = "PUT_ANUNCIOS";
export const DELETE_ANUNCIOS = "DELETE_ANUNCIOS";

/* EVERYTHING ELSE... */
export const GET_EMPLEOS = "GET_EMPLEOS";
